### ISSUE TITLE
pybabel fails to update under python-3.3

### ISSUE THREAD

**Issue by georgthegreat** [mitsuhiko/flask-babel#43]
TypeError is being thrown:

```
$ pybabel update -i messages.pot -d translations/
updating catalog 'translations/en/LC_MESSAGES/messages.po' based on 'messages.pot'
Traceback (most recent call last):
  File "/home/georg/env/main/bin/pybabel", line 9, in <module>
    load_entry_point('Babel==1.3', 'console_scripts', 'pybabel')()
  File "/home/georg/env/main/lib/python3.3/site-packages/babel/messages/frontend.py", line 1151, in main
    return CommandLineInterface().run(sys.argv)
  File "/home/georg/env/main/lib/python3.3/site-packages/babel/messages/frontend.py", line 665, in run
    return getattr(self, cmdname)(args[1:])
  File "/home/georg/env/main/lib/python3.3/site-packages/babel/messages/frontend.py", line 1130, in update
    width=options.width)
  File "/home/georg/env/main/lib/python3.3/site-packages/babel/messages/pofile.py", line 444, in write_po
    _write(comment_header + u'\n')
  File "/home/georg/env/main/lib/python3.3/site-packages/babel/messages/pofile.py", line 388, in _write
    fileobj.write(text)
TypeError: must be str, not bytes
```

**Comment by AnderUstarroz** [comment]
Still getting the same error when running **Babel** under Python 3.4

**Comment by jmagnusson** [comment]
I can confirm that po-file generation with Python 3.4 is broken. Following @georgthegreat fixes this.

Does anyone know how to make a new release for Flask-Babel that contains this fix and then be able to install it with pip? I could live with having to install it by pointing to a git repo.

**Comment by thanhson1085** [comment]
+1, please make a release

**Comment by ser** [comment]
please make a release, it still does not work with the last release in pypi :-1:

**Comment by mitsuhiko** [comment]
This should be fixed now.
